---
- hosts: es_hosts
  become: yes
  become_user: root
  pre_tasks:
    - name: install epel
      yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
    - name: install pip
      yum: name=python-pip
  roles:
    - { role: ansible-elasticsearch, es_instance_name: "{{ansible_hostname}}", es_heap_size: "1g", es_data_dirs: "/opt/elasticsearch",
        es_config: {
            discovery.zen.ping.multicast.enabled: false,
            discovery.zen.ping.unicast.hosts: "{{groups['master']|map('extract', hostvars, 'ansible_ssh_host')|list|join(':9300,')}}:9300",
            network.host: [_site_, _local_],
            http.port: 9200,
            transport.tcp.port: 9300,
            node.data: "{{ ansible_ssh_host in groups['data']|map('extract', hostvars, 'ansible_ssh_host')|list }}",
            node.master: "{{ ansible_ssh_host in groups['master']|map('extract', hostvars, 'ansible_ssh_host')|list }}",
            bootstrap.mlockall: false,
            cluster.name: "test-cluster" }
      }
  vars:
    es_version: "2.4.0"
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible
    es_plugins:
     - plugin: elasticsearch/license
       version: latest

- hosts: master
  tasks:
    - name: check that cluster status is green
      uri:
        url: "http://localhost:9200/_cluster/health?pretty"
        methods: GET
        status_code: 200
        body_format: json
      register: cl_status
      until: cl_status.json.status == "green"
      retries: 30
      delay: 10
